# Step 1: Use the official Node.js 14 image as a base
FROM node:18.18.0 as builder

# Step 2: Set the working directory inside the container
WORKDIR /app

# Step 3: Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Step 4: Copy the rest of your application's source code
COPY . /app

# Step 5: Install dependencies
RUN npm install yarn
RUN yarn install

# Step 6: Build your Nuxt.js application
RUN yarn build

# Step 7: Start with a fresh base image to reduce the image size
FROM node:18.18.0-slim

# # Step 8: Set the working directory in the new image
WORKDIR /app

# Step 9: Only copy the built artifacts and necessary files from the builder stage
COPY --from=builder /app/.nuxt ./.nuxt
COPY --from=builder /app/.output ./.output
COPY --from=builder /app/nuxt.config.ts .
COPY --from=builder /app/package*.json ./

# Step 10: Install production dependencies
RUN npm install yarn
RUN yarn install

# Step 11: Expose the port the app runs on
EXPOSE 3000

# Step 12: Define the command to run your app
CMD ["yarn", "start"]
